type: base
post: 
  description: The clear cache API allows to clear either all caches or specific cached associated with one ore more indices.
  queryParameters: 
    filter: 
      description: The API, by default, will clear all caches. Specific caches can be cleaned explicitly by setting filter, field_data or id_cache to true.
      type: boolean
    field_data: 
      description: The API, by default, will clear all caches. Specific caches can be cleaned explicitly by setting filter, field_data or id_cache to true.
      type: boolean
    id_cache: 
      description: The API, by default, will clear all caches. Specific caches can be cleaned explicitly by setting filter, field_data or id_cache to true.
      type: boolean
