type: base
get: 
  description: Multi GET API allows to get multiple documents based on an index, type (optional) and id (and possibly routing). The response includes a docs array with all the fetched documents, each element similar in structure to a document provided by the get API.
  body: 
    application/json: 
      schema: mgetReq
      example: !include ../examples/mgetReq-example.json
  responses: 
    200: 
      body: 
        application/json: 
