get: 
  description: |
    The multi search API allows to execute several search requests within the same API.
  body: 
    text/plain: 
      example: !include ../examples/msearchBody-example.txt
  responses: 
    200: 
      body: 
        application/json: 
post: 
  description: |
    The multi search API allows to execute several search requests within the same API.
  body: 
    text/plain: 
      example: !include ../examples/msearchBody-example.txt
  responses: 
    200: 
      body: 
        application/json: 
